version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2.7-jessie-node
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo ok

  publish-to-git:
    docker:
      - image: 18fgsa/cloud-foundry-cli
        environment:
          CF_API: https://api.fr.cloud.gov
          CF_ORG: sandbox-gsa
          CF_SPACE: aaron.borden
    steps:
      - checkout
      - run:
          name: Configure cf
          command: |
            cf api "$CF_API"
            cf auth "$CF_DEPLOY_USER" "$CF_DEPLOY_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
      - run:
          name: Publish to git
          # TODO monitor the results with cf logs and cf tasks
          command: cf run-task --name pootle-sync translate 'bin/sync-git.sh' -m 128m

workflows:
  version: 2
  continuous-integration:
    jobs:
      - test

  daily:
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - publish-to-git
